---
- name: monitor
  hosts: "monitor"
  become: true
  roles:
    - role: vault_accessor
    - role: monitor
  vars:
    consul_token: "{{ lookup('env', 'PROMETHEUS_CONSUL_TOKEN') }}"
    consul_ips: "{{ lookup('env', 'PROMETHEUS_CONSUL_IPS') | from_json }}"
    vault_token: "{{ lookup('env', 'PROMETHEUS_VAULT_TOKEN') }}"
