
---
# handlers file for ansible-role-fluentbit

- name: Restart Vector Service
  service:
    name: vector
    enabled: true
    state: restarted
  become: true
- name: Restart Consul Service
  service:
    name: consul
    enabled: true
    state: restarted
  become: true
