---
- name: Vector | Add Repository | Get Script
  get_url:
    url: https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh
    dest: /tmp/vector-installer.sh
    mode: 0755
- name: Vector | Add Repository | Run Script
  shell: /tmp/vector-installer.sh
- name: Vector | Add Repository | Remove Script
  file:
    path: /tmp/vector-installer.sh
    state: absent
