---
- name: Add fluent-bit apt key
  apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present
- name: Add fluent-bit repository
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/ubuntu/focal focal main'
    state: present
    filename: td-agent-bit
    update_cache: true
- name: Install fluentbit package
  package:
    name: td-agent-bit
    state: present
    update_cache: true
  notify: Restart Fluentbit service
  tags: ['install']
- name: Configure | Source td-agent-bit main conf
  template:
    src: td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644
  notify: Restart Fluentbit service
