---
- include: add_repo.yml
  when:
    - add_repo is defined
    - add_repo == true
- name: Vector | Install Package
  package:
    name: vector
    state: latest
    update_cache: true
  tags: ['install']
  notify: Restart Vector service
- name: Vector | Configuration | Create target directory
  file:
    path: /etc/vector
    state: directory
    mode: 0755
- name: Vector | Configuration | Generate Configuration
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: 0644
  notify: Restart Vector service
- name: Consul | Configuration | Telemetry Configuration
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/50.telemetry.hcl
    mode: 9644
  notify: Restart Consul Service
- include: docker_permission.yml
  when:
    - use_docker == true
